project:
  type: website

website:
  title: "Bradley Fern"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/bradfern_
      - icon: linkedin
        href: https://www.linkedin.com/in/bradley-fern-a10a6bab/
      - icon: github
        href: https://github.com/bfern
format:
  html:
    theme: cosmo
    css: styles.css



