---
title: Who is the best at running between the wickets?
date: "2024-10-28"
categories: [cricket, data science, r, visualisation]
---

Note to self: see ~/Downloads/rough.R for code that I have written so far.

Over the past few months, I've taken an interest in baseball analytics because there is so much cricket can learn from what has been done there. I've learn that base running is a large component of the game, which struck me as odd since running between the wickets is neglected in cricket. But should it be? In this post, I will quantify the effect that a strong runner between the wickets has upon the team.

To do this, I am going to use wagonwheel data of where a batter hits the ball and how many runs they end up scoring. I will then build a model that predicts the number of runs they are expected to score, and we can then compare these predictions to the actual runs scored for different batters.

Firstly, lets take a look at the dataset that I am using. I am using ball by ball data that has been put together by [Himanish Ganjoo](https://twitter.com/hganjoo_153). The dataset that I am using has been filtered so that it contains only the following:
* T20 Blast and The Hundred from 2015 to 2024.
* Matches played at the 18 major England and Wales stadiums (because some of the outgrounds that get used can have unusual dimensions)
* Balls from outside the powerplay (because this causes the distribution of runs to vary significantly)
* Balls that did not go for a boundary
* Balls with wagonwheel data (I'm assuming that these are only deliveries where the batter hit the ball)

## run script that does data manipulation, call it data_manipulation.R

Lets take a look at this wagonwheel data, using different colours to denote the number of runs ran.

## plot wagonwheel data with colours of runs ran

## some comments about this graph

Lets now think about building the model. I should include the following variables in the model:
* wagonX and wagonY (obviously)
* ground (grounds can vary in size, which means that smaller grounds will have less twos)
* bowl_kind (since I don't have fielding data, this helps give a proxy of where the fielders are positioned)
* bat_hand (this also helps gives a proxy of what the field is like)
* innings_balls_remaining (towards the later stages of a game, batters will take more risks)

To demonstrate the affect of the ground variable, below is a plot of the proportion of twos scored against the proportion of boundaries scored for the 18 first class grounds for all T20 blast deliveries since 2015:

## plot

I will use a random forest model, using the [randomForest](https://cran.r-project.org/web/packages/randomForest/index.html) package in R. You can see the full code for training the model from the data on my [GitHub](LINK TO MODEL TRAINING)

## model training

I now want to check that this model is giving us sensible predictions. Lets take a look at its predictions for deliveries at Edgbaston in our dataset.

## model prediction and graphing the output at edgbaston, add label to graph so people know where the bowlers end is

To be perfectly honest, I wasn't expecting the model to come out as good as this. The graphs make a lot of intuitive sense to anyone who knows T20 cricket for a variety of reasons:
* You can make out where the boundary fielders usually are, particuarly for the spinners - three on the leg side and two on the off.
* You can also make out fielding positions that are almost always on the edge of the ring - for example backward point and extra cover.
* The deep third man/deep fine leg positions score a lot more highly for spin compared to pace - there very rarely is a fielder on the boundary behind square for spinners.

So, given that we're happy with the model, lets see the results! Which batters score a lot more runs than expected? Lets take a look...

## top run scorers and some commentary about it

What about those who do a lot worse than expected

## bottom run scorers and some commentary about it

Given our analysis, can we say how many extra runs X contributes to Y? On average, these are the number of non boundary deliveries that each position is in for (so including both on strike and at the bowlers end) during a T20 match:

So if we were choosing between X and Y for position Z in the team, X is expected to contribute W extra runs to the team score because of his running ability.